##########  some useful info for tags   ##########

# [tags]: https://gelbooru.com/index.php?page=wiki&s=&s=view&id=25921
# [cheatsheet]: https://gelbooru.com/index.php?page=wiki&s=&s=view&id=26263
# [API]: https://gelbooru.com/index.php?page=wiki&s=view&id=18780

##################################################

tags = "cat 1girl rating:general" # tags for gelbooru, see `[tags]` and `[cheatsheet]`.
num_imgs = 100                    # the number of images you need to download. range: `1..=20_000`
download_dir = "images"           # the folder path to download images.
timeout = 15                      # download connecting timeout limit, `0` means no limit.
